Homework2
ElenaBakova/Homeworks-4sem pull request #2
Opened 2022-03-11 17:26 UTC by ElenaBakova

2022-03-19 16:30 UTC, DedSec256 requested changes
Есть небольшие замечания

2022-03-19 16:30 UTC, DedSec256 commented on Homework2/HW2/TreeMap.fs
> +let rec treeMap (binTree: Tree<'a>) (cont: 'a -> 'a) =
из любопытства, `cont` как здесь расшифровывается? (:

2022-03-19 16:30 UTC, DedSec256 commented on Homework2/HW2/InfinitySequence.fs
> +let seqence() = Seq.initInfinite(fun x -> x + 2) |> Seq.choose (fun x -> if primeCheck x then Some x else None)
очепятка!

2022-03-19 16:30 UTC, DedSec256 commented on Homework2/HW2/InfinitySequence.fs
> +let seqence() = Seq.initInfinite(fun x -> x + 2) |> Seq.choose (fun x -> if primeCheck x then Some x else None)
через `Seq.filter` было бы сильно проще (:

2022-03-19 16:30 UTC, DedSec256 commented on Homework2/HW2/InfinitySequence.fs
> +    number <> 1 && seq {2 .. int(sqrt(float number))} |> Seq.exists (fun x -> number % x = 0) |> not
тут больше подойдет `Seq.forall`

2022-03-21 22:37 UTC, ElenaBakova commented on Homework2/HW2/TreeMap.fs
> +let rec treeMap (binTree: Tree<'a>) (cont: 'a -> 'a) =
continuation. Написала как в конспекте, надо было переименовать

2022-03-23 16:53 UTC, DedSec256 approved these changes
👍

2022-03-23 17:01 UTC, merged